[package]
name = "barcode"
version = "0.1.0"
edition = "2021"
barcoders = "1.0.2"

[dependencies.pyo3]
version = "0.19.0"
features = ["auto-initialize"]

[dependencies]
rand = "0.8.4"
quirc = "0.0.1"
bardecoder = "0.4.1"
image = "0.24.6"
qrcode-generator = "4.1.8"
